# Generated by Django 4.1.4 on 2023-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
