# Generated by Django 4.1.4 on 2023-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('C', 'cash'), ('S', 'stripe')], max_length=1, null=True),
        ),
    ]
