# Generated by Django 4.1.4 on 2023-01-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
