# Generated by Django 4.1.4 on 2023-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
    ]
