# Generated by Django 4.1.5 on 2023-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(null=True, upload_to='work_image', verbose_name='imagen2'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(null=True, upload_to='work_image', verbose_name='imagen3'),
        ),
    ]
