# Generated by Django 4.1.5 on 2023-02-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_item_image_alter_item_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='work_image/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='work_image/', verbose_name='imagen2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='work_image/', verbose_name='imagen3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='work_image'),
        ),
    ]
