# Generated by Django 4.1.5 on 2023-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_item_image_alter_item_image2_alter_item_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='work_image'),
        ),
    ]
