# Generated by Django 4.1.5 on 2023-02-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_item_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='work_image'),
        ),
    ]
